### ISSUE TITLE
how to use in vue or vue3?

### ISSUE THREAD

**Issue by wssnail** [saurabh-prosoft/flow-connect#7]
in vue2, i got the error >         Module not found: Error: Can't resolve 'flow-connect/cjs/standard-nodes'

**Comment by saurabh-prosoft** [comment]
@wssnail New version released with the fixes, use v1.0.13.

For using StandardNodes you need to add dependency for that specific package first,
for e.g. to use the `Timer` node,  add common package to your dependencies `npm i @flow-connect/common`, then:

`import { Timer } from '@flow-connect/common`

Check this example for reference: https://codesandbox.io/s/flow-connect-with-vue-se0ui0

**Comment by wssnail** [comment]
> @wssnail New version released with the fixes, use v1.0.13.
> 
> For using StandardNodes you need to add dependency for that specific package first, for e.g. to use the `Timer` node, add common package to your dependencies `npm i @flow-connect/common`, then:
> 
> `import { Timer } from '@flow-connect/common`
> 
> Check this example for reference: https://codesandbox.io/s/flow-connect-with-vue-se0ui0

thank you，it worked in vue3，I will learn how to use it。However, the click position of the connection point and button on the node is not very accurate

**Comment by saurabh-prosoft** [comment]
Thanks for the feedback ! new fixes coming up in the next release
